### ISSUE TITLE
Non-deterministic "invalid JUMP" error when calling newly created contract

### ISSUE THREAD

**Issue by PeterBorah** [ConsenSys-archive/ganache-cli-archive#196]
When calling a function on a newly created contract, testrpc will occasionally report an "invalid JUMP" EVM error. This behavior does not appear in Geth, suggesting that it's a testrpc or ethereumjs bug, rather than a bug in the Solidity compiler or EVM spec.

 

## Expected Behavior

Invalid JUMP errors should not be thrown during normal execution.

## Current Behavior

Non-deterministically, some calls trigger an "invalid JUMP" error. This appears to only happen if you both:

1) Create a new contract, and
2) In the same _transaction_ (not necessarily the same call), make a call to that new contract

I've run a variety of experiments to determine that those are the necessary and sufficient conditions. Details available if desired. :)

While it's hard to be sure given that it's non-deterministic and geth is slow, I am pretty confident that no such bug appears when running the same tests against geth. I've run geth for several thousand iterations without incident, while the bug generally appears on testrpc within a few hundred iterations at most.

(Anecdotally, I'm pretty sure the distribution of how long it takes the bug to be encountered is non-uniform. It seems ~logarithmic, in such a way that you seem about equally likely to encounter the bug in any of the following buckets: 0-50, 51-300, 301-800. No idea what this could mean, and I haven't done any rigorous statistics, but it seemed interesting enough to report.)

## Possible Solution

Since this is an EVM-level error, it is presumably in the EVM implementation somewhere. 

## Steps to Reproduce (for bugs)

The following contracts are a minimal test case:

    pragma solidity ^0.4.3;
    
    import "./Child.sol";
    
    contract Creator {
      function createAndCall() {
        Child child = new Child();
        child.someFunction();
      }
    }

    pragma solidity ^0.4.3;
    
    contract Child {
      function someFunction() {
      }
    }

The following Solidity test will call `createAndCall()` in an infinite loop until the bug is hit. In my experience this happens within ~700 iterations at most, often much less.

    contract('Creator', function(accounts) {
      recursively_call = function(iteration) {
        console.log(iteration);
        Creator.deployed().createAndCall().
          then(function() { return recursively_call(iteration + 1) });
      }
    
      it.only("Can create and call a child function", function(done) {
        return recursively_call(0);
      });
    });

## Context

In my current project, I have a factory contract that creates contracts and automatically calls certain functions on them. My test suite is big enough and calls this factory often enough that it usually hits the bug at least once per run.

## Your Environment

EthereumJS TestRPC v3.0.0
Truffle v3.0.0-2
MacOS X

**Comment by thiagodelgado111** [comment]
Apparently, I'm facing the same issue here, from 5 times that I ran my test suite against testrpc it failed 3 times with the same error message.

```
Error: VM Exception while processing transaction: out of gas
      at Object.InvalidResponse (/Users/thiagodelgado/.nvm/versions/node/v6.9.1/lib/node_modules/truffle/node_modules/ether-pudding/node_modules/web3/lib/web3/errors.js:35:16)
      at /Users/thiagodelgado/.nvm/versions/node/v6.9.1/lib/node_modules/truffle/node_modules/ether-pudding/node_modules/web3/lib/web3/requestmanager.js:86:36
      at request.onreadystatechange (/Users/thiagodelgado/.nvm/versions/node/v6.9.1/lib/node_modules/truffle/node_modules/web3/lib/web3/httpprovider.js:114:13)
      at dispatchEvent (/Users/thiagodelgado/.nvm/versions/node/v6.9.1/lib/node_modules/truffle/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591:25)
      at setState (/Users/thiagodelgado/.nvm/versions/node/v6.9.1/lib/node_modules/truffle/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:610:14)
      at IncomingMessage.<anonymous> (/Users/thiagodelgado/.nvm/versions/node/v6.9.1/lib/node_modules/truffle/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:447:13)
      at endReadableNT (_stream_readable.js:974:12)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

## Environment

EthereumJS TestRPC v3.0.0
Truffle v2.1.0
MacOS X
Node v5.5 / v6.9.1

**Comment by simondlr** [comment]
I'm consistently experiencing invalid JUMP for the same reason.

> I have a factory contract that creates contracts and automatically calls certain functions on them.

Same setup as this. In my circumstance, I've written tests in Solidity (in Truffle) that work fine and have never seen this issue.

The issue comes in when deploying from web3/js. Using solc 0.4.3. Unlike above, it happens consistently. getData works fine and returns the expected result. Only when issuing the transactions does it cause an invalid JUMP.

Because I haven't experienced it with Solidity tests, I suspect it _might_ be Truffle that's doing something weird?

**Comment by PeterBorah** [comment]
> Because I haven't experience it with Solidity tests, I suspect it might be Truffle...

Hmmm... This would surprise me, given that the error shows up in the testrpc log, and only happens when certain conditions are met inside the EVM (which Truffle shouldn't know about). But I suppose it's possible!

**Comment by simondlr** [comment]
Yeah. That would be surprising. Might be solc 0.4.3 and how it interplays with Truffle? Dunno.

My issue might be something else that causes an invalid jump. The causes are similar though. Occurs with a factory contract.

**Comment by simondlr** [comment]
This looks related and the vm was bumped yesterday. 

https://github.com/ethereumjs/ethereumjs-vm/issues/88

Will give this a spin tomorrow and see if it fixes it.

**Comment by simondlr** [comment]
When I upgraded the vm (to 2.0.1) and added this change (for another bug), I can confirm that I don't receive invalid jumps anymore. https://github.com/ethereumjs/testrpc/issues/197

**Comment by simondlr** [comment]
I can confirm that with the upgrade to the latest vm (2.0.1) and a small change here (https://github.com/ethereumjs/testrpc/issues/197), I no longer get invalid jumps.

**Comment by jmdfm** [comment]
Just published `testrpc@3.0.2` which upgrades the `ethereumjs-vm` dependency to `2.0.1` - should fix this issue.

**Comment by tcoulter** [comment]
@simondlr Can you retest with `v3.0.2`? @jmd noticed an issue with your branch that showed ethereumjs-vm wasn't instantiated correctly; in fact, it was instantiated with a default blockchain object and _not the blockchain object managed by the testrpc_(!). If the testrpc's blockchain object is the root cause of the issue, then regretfully the issue would still exist. 

If anyone else could confirm as well it'd be much appreciated.

**Comment by simondlr** [comment]
I tested with Truffle's migrations and it worked fine, but trying to test with Metamask, but running into new issues when they changed their gas estimation with the latest build. A rabbit hole has opened up.

**Comment by simondlr** [comment]
Someone else should test this as well. Haven't had chance to test this with contract-creating-contract issue that caused the invalid jump.

**Comment by elenadimitrova** [comment]
I can confirm I am still getting the `Invalid jump` with 3.0.2

**Comment by PeterBorah** [comment]
I can confirm that this seems to have fixed my bug. Both my actual test suite and my minimal test case seem fine using the latest testrpc.

**Comment by tcoulter** [comment]
Hot damn. Thanks @PeterBorah! Closing.

**Comment by tcoulter** [comment]
Also, thanks @simondlr!

**Comment by ownageio** [comment]
So this one seems to reared it's head again for me with the latest version. I'm using `testrpc` in deterministic mode so I get a 100% reproduction rate for the problem with @PeterBorah's smart contracts.

Here's the setup I'm using:

`testrpc -d -m "ownage test mnemonic crypto coin currency tech games money free netwo
rk hex" -h localhost -p 8545`

With the following library versions:

`truffle@2.1.1`
`web3@0.17.0-beta`
`ether-pudding@3.2.0`
`solc@0.4.4`
`ethereumjs-testrpc@3.0.2`

And using the first generated account (it's the same for any of them actually):

`Available Accounts
==================
(0) 0x98c03d0460abc9d66174d03bc365a1c8e4e459cc
...`

It produces the following error (logs extract):

`eth_sendTransaction
[testrpc] : OUT : 
[testrpc] : OUT :   Transaction: 0x3d15d0da025a1ef3fbc723f5eed70503319f8ede85e25fae42d54624a9fdcee6
[testrpc] : OUT :   Gas usage: 0x015f90
[testrpc] : OUT :   Block Number: 0x44
[testrpc] : OUT :   Block Time: Thu Nov 24 2016 14:29:48 GMT+0000 (GMT)
[testrpc] : OUT :   Runtime Error: invalid JUMP at ede9f39ab4dfe39709d58c08cc8e37b3827ca0ae7a27c4143e6e2d2fdbd51ec7/09f68e7a4b0055f4d6080eff9d35e42e74866760:329`
