### ISSUE TITLE
web3.eth.getBalance returns "missing trie node"

### ISSUE THREAD

**Issue by fivetwentyseven** [ConsenSys-archive/ganache-cli-archive#466]
```
> web3.eth.blockNumber
1244088
> web3.eth.getBalance('0xffffa5fb6c9a9a92ac504a5d3a1099ccdb8e566e')
Error: Error: missing trie node cb254d3cd9d33fcd5139c5493eaa47481697ceab489bc4de5c2b660b9989aa92 (path )
    at Object.InvalidResponse (/usr/local/lib/node_modules/ganache-cli/build/cli.node.js:16905:16)
    at /usr/local/lib/node_modules/ganache-cli/build/cli.node.js:77175:36
    at XMLHttpRequest.request.onreadystatechange (/usr/local/lib/node_modules/ganache-cli/build/cli.node.js:83067:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/usr/local/lib/node_modules/ganache-cli/build/cli.node.js:83798:18)
    at XMLHttpRequest._setReadyState (/usr/local/lib/node_modules/ganache-cli/build/cli.node.js:84088:12)
    at XMLHttpRequest._onHttpResponseEnd (/usr/local/lib/node_modules/ganache-cli/build/cli.node.js:84243:12)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/ganache-cli/build/cli.node.js:84203:24)
    at IncomingMessage.emit (events.js:165:20)
    at endReadableNT (_stream_readable.js:1101:12)
    at process._tickCallback (internal/process/next_tick.js:152:19)
    at Object.InvalidResponse (/home/node_modules/web3/lib/web3/errors.js:38:16)
    at RequestManager.send (/home/node_modules/web3/lib/web3/requestmanager.js:61:22)
    at Eth.send [as getBalance] (/home/node_modules/web3/lib/web3/method.js:145:58)
> 

```

**Comment by Asone** [comment]
Hi @use-r, some problems with tries have been addressed.

You'll find most of those in #453, mostly  [this comment](https://github.com/trufflesuite/ganache-cli/issues/453#issuecomment-354877557). 

Another related issue was #417 . 

Some developpers are working around this problem, maybe yours is related to the same bug.

**Comment by benjamincburns** [comment]
@use-r thanks for reporting this, but why did you close? From your description it seems likely that we're just not returning a zero balance when the account isn't found. This is separate from the bugs that @Asone mentioned above and should be fixed if still present.

**Comment by Asone** [comment]
Sorry if i lead to some confusion, that was not my intention, just intended to provide some information in case it could be useful. 

Obviously, it was a mistake, i'll remain silent until i get in a deeper understanding of those topics. 

Again, sorry

**Comment by benjamincburns** [comment]
No need to apologize, @Asone - I thought your comment was quite helpful.

**Comment by rustyx** [comment]
This is not a web3 issue but a Geth issue. The JSON RPC returns this error:

```
{
  "jsonrpc": "2.0",
  "id": 1,
  "error": {
    "code": -32000,
    "message": "missing trie node cb254d3cd9d33fcd5139c5493eaa47481697ceab489bc4de5c2b660b9989aa92 (path )"
  }
}
```

**Comment by Mojicode** [comment]
Is there any solutions for this problem now ?

**Comment by Mojicode** [comment]
> Is there any solutions for this problem now ?

I know my issue now, **I start geth with fast mode, and I use history blocknumber to get address balance**, so it report the "missing trie node". **When I use the latest blockNumber to get addr balance, it is OK.** Hope it's useful for you.

**Comment by davidmurdoch** [comment]
Thanks, @Mojicode for the additional information! Since this is an external error due to the external forked node not being fully synced i'm going to close this issue.
