### ISSUE TITLE
testrpc 2.0.0 - cannot find module 'memdown'

### ISSUE THREAD

**Issue by mowliv** [ConsenSys-archive/ganache-cli-archive#60]
Trying to get testrpc (2.0.0) working on an ubuntu virtualbox, and getting this error when I run it:

```
mowliv@u4:~$ testrpc
module.js:341
    throw err;
    ^

Error: Cannot find module 'memdown'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/usr/lib/node_modules/ethereumjs-testrpc/node_modules/merkle-patricia-tree/baseTrie.js:3:17)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)

```

Have tried npm update -g and sudo npm install -g memdown but those didn't help. Maybe I'm being bitten by a major new (2.0.0) release?

**Comment by tcoulter** [comment]
Hmm, this shouldn't be an issue as merkle-patricia-tree (the dependency that requires memdown) has been a dependency from the start. Can you simply run `npm install -g ethereumjs-testrpc` again? I've been running into this a lot lately where npm skips over some dependencies, which are fixed with rerun.

For my purposes, which version of Node are you using?

**Comment by tcoulter** [comment]
Also, running `sudo` vs. non-sudo can cause interesting results. I'd recommend not using sudo if you can, but that's mostly me repeating what I've heard from others.

**Comment by mowliv** [comment]
Thanks for the speedy response!

Tried running that again w/o sudo (failed) and with sudo -- but didn't resolve problem. 

node 5.10.0
ubuntu 14.04 LTS
virtualbox 5.0.16 on a Mac

```
mowliv@u4:~$ sudo npm install -g ethereumjs-testrpc
[sudo] password for mowliv: 
/usr/bin/testrpc -> /usr/lib/node_modules/ethereumjs-testrpc/bin/testrpc
/usr/lib
└─┬ ethereumjs-testrpc@2.0.0 
  ├─┬ web3@0.15.3
  │ └── bignumber.js@2.0.7  (git+https://github.com/debris/bignumber.js.git#94d7146671b9719e00a09c29b01a691bc85048c2)
  └─┬ web3-provider-engine@6.1.0
    └─┬ request@2.70.0 
      ├── bl@1.1.2 
      └── qs@6.1.0 

```

**Comment by tcoulter** [comment]
That's super odd. I'll have to fire up an ubuntu VM and try it out myself.

**Comment by tcoulter** [comment]
Hmm, I was about to point you to your own ticket (https://github.com/ethereumjs/testrpc/issues/57) until I realized you were the author. Ugh, sorry about the installation issues.

**Comment by mowliv** [comment]
Thanks. That's pretty funny :)

**Comment by IamSandipC** [comment]
any update? facing same issue

**Comment by tcoulter** [comment]
Unfortunately I haven't found anyone who's fixed this issue. Odd request: Could you _downgrade_ your node version to 5.5? I'm not sure if it'll help, but I know there was another person who had an issue that was solved via a downgrade from 5.10. I'm not sure if this will be the solution, but I'd be interested to know if it is.

**Comment by IamSandipC** [comment]
No luck with node 5.5 even... :(

**Comment by tomsib2001** [comment]
Same problem here, node 4.4.3, npm 2.15.1, Ubuntu 14.04
Solved it using https://github.com/mcollina/mosca/issues/413

**Comment by fortran01** [comment]
This one worked for me http://stackoverflow.com/a/31861021/422842. See the `npm cache clear` comment.

**Comment by ntarora** [comment]
`cd /usr/local/lib/node_modules/ethereumjs-testrpc/`
 `npm test` this will probably fail
while still in the directory `sudo npm install`

run `testrpc`

if memdown still persist `sudo npm install memdown` while in the etheruemjs-testrpc directory

then run `testrpc` again should work

**Comment by hasanqusay** [comment]
I did what you said and this is what I got :((((

http://imgur.com/a/wAv0u

**Comment by muguruza** [comment]
Same problem here: node v0.10.25, npm 1.3.10, Ubuntu 14.04

Unsuccessfully tried 

> cd /usr/local/lib/node_modules/ethereumjs-testrpc/
> npm test this will probably fail
> while still in the directory sudo npm install
> 
> run testrpc
> 
> if memdown still persist sudo npm install memdown while in the etheruemjs-testrpc directory
> 
> then run testrpc again should work

and also

> This one worked for me http://stackoverflow.com/a/31861021/422842. See the npm cache clear comment.

**Comment by fractalDimension** [comment]
Ok I tried everything in this thread and also some other random fixes from elsewhere so I can't be certain why mine is working now but here's some things to try:
- install memdown globally (last thing I did before it started to work)
  - `npm install -g memdown`
- go into testrpc's node_modules folder and run npm install from within the merkle-patricia-tree folder
  - `cd /usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/merkle-patricia-tree/`
  - `npm install`

Keep trying things because you can get it to work!

**Comment by tcoulter** [comment]
Thanks for everyone's input on this ticket. I'm doing housekeeping on open issues, and have realized that installation issues are best handled via a conversation on gitter, since everyone's configuration is different. I'm going to close this ticket, but definitely follow up in the ethereumjs's gitter if you're still having issues! http://gitter.im/ethereum/ethereumjs-lib
